### ISSUE TITLE
Error in the routing for the gke usage

### ISSUE THREAD

**Issue by jsdorababu** [BESTSELLER/backstage-plugin-gkeusage#154]
am trying to integrate the gke usage plugin into our application build on backstage. Configured/consumed the plugin as per the instructions shared in the repo.
but seeing below error 

Cannot route to routeRef{type=absolute,id=GKE Usage Metering Entity Content} with parent routeRef{type=absolute,id=Entity} as it has parameters

Could you help on this?

**Comment by wrighbr** [comment]
What does your packages/app/src/components/catalog/EntityPage.tsx look like it should be something like the below
```
    <EntityLayout.Route
      path="/gke-usage"
      title="GKE Usage"
      if={isGkeUsageMeteringAvailable}
    >
      <EntityGKEUsageContent />
    </EntityLayout.Route>
```

**Comment by Gaardsholt** [comment]
Closing this issue as there has been no replies in the issue for some time now.
